language: node_js
node_js:
- '8'
script:
- set -e
- npm run test
- npm run coveralls
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- npm config set git-tag-version=false
- NPM_VERSION=$(npm version patch)
- git commit -a -m "${NPM_VERSION:1}" -m "[ci skip]"
- git remote remove origin
- git remote add origin https://${GITHUB_TOKEN}@github.com/xpl/get-source.git
- git push origin HEAD:master
deploy:
  provider: npm
  email: rocket.mind@gmail.com
  api_key:
    secure: sWAu+QsEwpE0x/MAKsCEJz7XynuI5rIM9/WPBx4wHWMzn1fQ2koncxhTJ4yiYL0pNDkvyeGHQyNWoL+PSvr0BwrcBWkC17N+UCTugOoe37p4sR8pMbvxOJ4jWOu8Vz/xjwmzVATIf4wBMvGIPnznMEOd6+ou+bR0mHZV5Q0F+GsJPKbd87rpJUjoG65sRH80YR+F+wRfS+JDJlCOuuhbfDR/iiRN4eF60HBy5ByS1vh6xO96tHeQJfemGflNJPaL1E7Tze6k1NevR+Vn51osJSyU+fOzdIzqC79FxgJBbDmb2GjlOi2Nsf9caxbbbsPfUpVsOhvQWK1mq0rFfR/IMztBW4ZpoSt6QCuvw3zy9bwSpMe3IjJDx6sQCehdHzofFPHZTRjMyubmtQNXU4tjwk6253ETt8zluJL/SSoK6PBhtlMG9bdZjeK3Z1ygyoecTLzbbUf6Ui+2ZHXf0QFqryI3hVPS+bFL12hOJTZ3XpY/Yhx/sq4EqN9yEJmE5Dz0BxOMWVRYX5BlmuUuAh6lEKrG4SPeH6O01PeB76Xwfq38CAU+GSSyC1Wtyb+IZ7vf/qTDEDxFFpZ8yMUUB5KDaCK8XgJuuRrybdZAJvYNtYypntUL/Tf3c4/0llk76zBtetY6UJbWv2yMLqIOvphwr8tStFoJJxfBqvKSxEPX2sg=
env:
  global:
    secure: SXc3ilPr7p+uac/b3ibx27zFEuKotjA0FLHkkFaU5Y74Ek++Yh++cmBbXjz8yS2XtaEmvr+EL/Z7cUsD7hbs787+lyc16AJNEf1l3PKwsFx7djsOBdXFf0mVPhmlx2BbAtgrVylPlVM0yzBDUTWOm2lFtMFp8v2vjJeSnePaWV2Gf7T4hpm4S4U0fXeVRFynFIDo+TfyJoNG6zg6iuUcIjiY5zrvE8U6pg3TtRUaQx8+JWZYdukiKEjPZ2mUHHGaHDRouM99wFz7Y1WTBkxYvyIQFNuf9zzJ/IRMFiLMhxPvSbIYHpNtimCWjYL/Hw105BWOxoTOFa2lsRT5dJAxv3LfroWrEG6vnV5BeJ35Ogcy4Mqf0N3lrMjo/vUgbn6nP2MTyADqBjNdJ0T6tqRSY4sE2M0nXddC/9/ONHOnqzOtAxqS72MJ93ZzSJ0VvMIaf2rygAnIHVHe7mzV3EEhs6l5APQYybYWI8bLD8A75LZeBG1tSBvdPdf5ny6l1GSyoQ1qIntfrl/FcGiJKbGVRl6by/XdRIGA9HOenOHdBzLrB58VF0NkOKzmizlu3O51LW21Yt/HwPRAoGb9t/7KAOT6otKplIk8qy/tTzIc0fZm6mG8FmRQsisIrfWTiWh37jSZU9FGdNGkF/tjjZ/bmEPiJ56fWiXvzVv9CQAeF/0=
